sudo: required

language: node_js
node_js:
  - "11.10"

# before_install:
  # - cd deployment
branches:
  only:
    - master

services:
  - docker

script: ./deployment/build.sh test

before_deploy:
  - docker --version
  - pip install --user awscli
  - ./deployment/build.sh docker_image_build $ENV $IAM_ID

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: $AWS_REGION  
  app: "app-beanstalk"
  env: "app-beanstalk-env"
  bucket_name: "app-travis-eb"
  on:
    branch: master

after_deploy:
  - echo "Elastic Beanstalk is deploying..."

notifications:
  email:
    recipients:
      - ladmusician.kim@gmail.com
