language: node_js
node_js:
  - "11.10"

sudo: required

# before_install:
  # - cd deployment
branches:
  only:
    - master

script: ./deployment/build.sh test

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:/$HOME/.local/bin
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - ./deployment/build.sh docker_image_build $ENV $IAM_ID

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: $AWS_REGION  
  app: "app-beanstalk"
  env: "app-beanstalk-env"
  bucket_name: "app-travis-eb"
  on:
    branch: master

after_deploy:
  - echo "Elastic Beanstalk is deploying..."

notifications:
  email:
    recipients:
      - ladmusician.kim@gmail.com
