language: node_js
node_js:
  - "10.14"
before_install:
  - cd app
branches:
  only:
    - master
#script: deployment/build.sh
notifications:
  email:
    recipients:
      - ladmusician.kim@gmail.com
